name: Release

on:
  release:
    types: [created]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ${{ github.workspace }}\PapyrusPlugin.sln

jobs:
  Release:
    runs-on: windows-latest
    strategy:
      matrix:
        build_platform: [x64, x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Update build number
        working-directory: ${{ github.workspace }}\src\Plugin\Common
        run: (gc Resources.hpp) -replace 'BUILD_NUMBER    0', 'BUILD_NUMBER    ${{ github.run_number }}' | Out-File -encoding ASCII Resources.hpp

      - name: Build plugin DLL and create packages
        working-directory: ${{ github.workspace }}\dist
        run: |
          msbuild /m /p:Configuration=Release /p:Platform=${{ matrix.build_platform }} ${{ env.SOLUTION_FILE_PATH }}
          copy bin\${{ matrix.build_platform }}\Papyrus.dll .
          & "C:\Program Files\7-Zip\7z.exe" a PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}.zip Papyrus.dll Papyrus.xml extras
          & "C:\Program Files\7-Zip\7z.exe" a PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}-with-manuals.zip Papyrus.dll Papyrus.xml extras ..\*.md

      - name: Upload release package
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}.zip
          asset_name: PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}.zip
          asset_content_type: application/zip

      - name: Upload release package with manuals included
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}-with-manuals.zip
          asset_name: PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}-with-manuals.zip
          asset_content_type: application/zip

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          github_token: ${{ github.token }}
          update_release_body: true
          files: |
            PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}.zip
            PapyrusPlugin-${{ github.event.release.tag_name }}-${{ matrix.build_platform }}-with-manuals.zip
